select * from customer limit 20
--Q1. What is the total revenue
--generated by male vs. female customers?
select gender ,sum(purchase_amount) as revenue
from customer
group by 1;

--Q2 . Which customers used a discount but still, spend more thsn the average purchase amount?
select customer_id , purchase_amount
from customer 
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer);

-- Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average product rating"
from customer
group by 1
order by 2 desc
limit 5;

--Q4. compare the average purchase amount between standard and express shipping .
select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by 1;

--Q5. do subscriber customer spend more ? 
-- compare average spend and total revenue 
-- between subscribe and non-subscribes.

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer 
group by 1
order by 3,2 desc;

-- Q6. which 5 products have the highest 
-- percentage of purchase with discount applied?

select item_purchased,
round(100*sum(case when discount_applied ='Yes' then 1 else 0 end)/count (*) ,2) as discount_rate
from customer
group by 1
order by 2 desc
limit 5;

-- Q7. segment customer into new , returing and loyal based on
--     there total number of previous purchases, and show the count of each segment.

with customer_type as(
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment,count(*) as "Number of customers"
from customer_type 
group by 1;


--Q8. What are the top 3 most purchased products within each category? 

with item_counts as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by 1,2
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

-- Q9. are customer who are repeat buyers (more then 5 previous purchase) also likely to subscribe?

select subscription_status,
count(customer_id ) as repeat_buyers
from customer
where previous_purchases> 5
group by 1;

-- Q10. what is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by 1
order by 2 desc;



















